version: '3.3'
services:
  backend:
    image: dto80/se234-lab12
    ports:
      - 8101:8080
    volumes:
      - type: bind
        source: /home/ubuntu/document/data.xlsx
        target: /data
  frontend:
    image: yanhang1/234-lab12-frontend
    ports:
      - 8102:80